version: '3.7'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
